2018-08-25 00:53:04.755 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 00:53:04.778 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 00:53:04.778 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 00:53:04.778 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 00:53:04.778 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 00:53:04.857 -03:00 [DBG] Starting token cleanup
2018-08-25 00:53:12.945 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 00:53:16.712 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 00:53:20.498 -03:00 [INF] Clearing 0 tokens
2018-08-25 00:53:21.766 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 00:53:21.791 -03:00 [INF] Identity.External was not authenticated. Failure message: Unprotect ticket failed
2018-08-25 00:54:24.762 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 00:54:24.783 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 00:54:24.783 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 00:54:24.783 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 00:54:24.784 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 00:54:24.862 -03:00 [DBG] Starting token cleanup
2018-08-25 00:54:31.752 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 00:54:34.259 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 00:54:39.147 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 00:54:39.169 -03:00 [INF] Identity.External was not authenticated. Failure message: Unprotect ticket failed
2018-08-25 00:56:47.685 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 00:56:47.705 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 00:56:47.706 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 00:56:47.706 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 00:56:47.706 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 00:56:47.780 -03:00 [DBG] Starting token cleanup
2018-08-25 00:56:55.908 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 00:56:59.439 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 00:57:04.930 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 00:57:04.952 -03:00 [INF] Identity.External was not authenticated. Failure message: Unprotect ticket failed
2018-08-25 01:00:03.248 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:00:03.268 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:00:03.268 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:00:03.268 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:00:03.268 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:00:03.350 -03:00 [DBG] Starting token cleanup
2018-08-25 01:00:06.552 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:00:08.550 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:00:13.191 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:00:13.213 -03:00 [INF] Identity.External was not authenticated. Failure message: Unprotect ticket failed
2018-08-25 01:05:29.974 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:05:29.995 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:05:29.995 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:05:29.995 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:05:29.995 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:05:30.081 -03:00 [DBG] Starting token cleanup
2018-08-25 01:05:39.482 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:07:32.443 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:11:24.419 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:12:32.339 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:12:32.360 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:12:32.360 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:12:32.360 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:12:32.361 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:12:32.442 -03:00 [DBG] Starting token cleanup
2018-08-25 01:12:41.596 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:12:50.887 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:12:57.519 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:14:28.519 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`1[Equinox.Domain.Commands.User.RegisterNewUserWithoutPassCommand]. Register your handlers with the container. See the samples in GitHub for examples. ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Equinox.Infra.Data.Context.EquinoxContext]' while attempting to activate 'Equinox.Infra.Data.Context.EquinoxContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
   --- End of inner exception stack trace ---
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`1.<>c__DisplayClass0_0.<<Handle>g__Handler|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Equinox.UI.SSO.Controllers.Account.AccountController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims) in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 529
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 196
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:14:47.650 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-25 01:14:47.669 -03:00 [DBG] Stopping token cleanup
2018-08-25 01:15:43.183 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:15:43.204 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:15:43.204 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:15:43.204 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:15:43.204 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:15:43.293 -03:00 [DBG] Starting token cleanup
2018-08-25 01:15:46.324 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:15:47.577 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:15:52.887 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:16:01.129 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`1[Equinox.Domain.Commands.User.RegisterNewUserWithoutPassCommand]. Register your handlers with the container. See the samples in GitHub for examples. ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Equinox.Infra.Data.Context.EquinoxContext]' while attempting to activate 'Equinox.Infra.Data.Context.EquinoxContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
   --- End of inner exception stack trace ---
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`1.<>c__DisplayClass0_0.<<Handle>g__Handler|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Equinox.UI.SSO.Controllers.Account.AccountController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims) in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 529
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 196
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:16:10.993 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-25 01:16:11.007 -03:00 [DBG] Stopping token cleanup
2018-08-25 01:17:29.226 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:17:29.246 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:17:29.246 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:17:29.247 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:17:29.247 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:17:29.326 -03:00 [DBG] Starting token cleanup
2018-08-25 01:17:32.473 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:17:33.604 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:17:38.719 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:18:00.468 -03:00 [INF] User created a new account with password.
2018-08-25 01:18:03.194 -03:00 [INF] User created a new account with password.
2018-08-25 01:18:13.560 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at IdentityServer4.AspNetIdentity.UserClaimsFactory`1.CreateAsync(TUser user) in C:\local\identity\server4\AspNetIdentity\src\IdentityServer4.AspNetIdentity\UserClaimsFactory.cs:line 28
   at Microsoft.AspNetCore.Identity.SignInManager`1.CreateUserPrincipalAsync(TUser user)
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 212
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:18:44.939 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:18:46.115 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:18:50.801 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:20:12.921 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:20:12.941 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:20:12.941 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:20:12.941 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:20:12.941 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:20:13.017 -03:00 [DBG] Starting token cleanup
2018-08-25 01:20:15.996 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:20:17.070 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:20:21.567 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:20:41.478 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`2.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at IdentityServer4.AspNetIdentity.UserClaimsFactory`1.CreateAsync(TUser user) in C:\local\identity\server4\AspNetIdentity\src\IdentityServer4.AspNetIdentity\UserClaimsFactory.cs:line 28
   at Microsoft.AspNetCore.Identity.SignInManager`1.CreateUserPrincipalAsync(TUser user)
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 212
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:21:11.974 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:21:13.060 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:21:19.731 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:22:22.967 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`2.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at IdentityServer4.AspNetIdentity.UserClaimsFactory`1.CreateAsync(TUser user) in C:\local\identity\server4\AspNetIdentity\src\IdentityServer4.AspNetIdentity\UserClaimsFactory.cs:line 28
   at Microsoft.AspNetCore.Identity.SignInManager`1.CreateUserPrincipalAsync(TUser user)
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 212
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:22:25.642 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-25 01:22:25.652 -03:00 [DBG] Stopping token cleanup
2018-08-25 01:58:41.295 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:58:41.318 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:58:41.319 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:58:41.319 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:58:41.319 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:58:41.409 -03:00 [DBG] Starting token cleanup
2018-08-25 01:58:44.870 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:58:44.888 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Equinox.Infra.CrossCutting.Identity.Services.UserService' while attempting to activate 'Equinox.UI.SSO.Controllers.Account.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-25 01:59:45.942 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-25 01:59:45.967 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-25 01:59:45.968 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-25 01:59:45.968 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-25 01:59:45.968 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-25 01:59:46.077 -03:00 [DBG] Starting token cleanup
2018-08-25 01:59:49.799 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-25 01:59:51.060 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-25 01:59:56.320 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-25 01:59:57.463 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Google",
  "ProviderUserId": "102696868227620762147",
  "SubjectId": "cabce51c-9883-4207-965c-3d287ea3c185",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGA8UA3FGG1:00000004",
  "TimeStamp": "2018-08-25T04:59:57Z",
  "ProcessId": 15408,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-25 01:59:57.484 -03:00 [DBG] Augmenting SignInContext
2018-08-25 01:59:57.485 -03:00 [DBG] Adding amr claim with value: external
2018-08-25 01:59:57.490 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-25 01:59:57.495 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-25 01:59:57.552 -03:00 [DBG] 0 persisted grants found for cabce51c-9883-4207-965c-3d287ea3c185
2018-08-25 02:00:48.216 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-25 02:00:48.240 -03:00 [ERR] Unexpected exception in SocketConnection.StartAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
2018-08-25 02:00:48.240 -03:00 [ERR] Unexpected exception in SocketConnection.StartAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
2018-08-25 02:00:48.242 -03:00 [DBG] Stopping token cleanup
2018-08-26 10:16:57.490 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 10:16:57.512 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 10:16:57.514 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 10:16:57.514 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 10:16:57.515 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 10:16:57.649 -03:00 [DBG] Starting token cleanup
2018-08-26 10:16:59.751 -03:00 [ERR] An error occurred using the connection to database 'Usuarios' on server '.'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
2018-08-26 10:16:59.822 -03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'Equinox.Infra.CrossCutting.Identity.Context.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
2018-08-26 10:16:59.853 -03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'Equinox.Infra.CrossCutting.Identity.Context.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
2018-08-26 10:16:59.887 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Usuarios" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.AspNetCore.Identity.SignInManager`1.ValidateSecurityStampAsync(ClaimsPrincipal principal)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator`1.ValidateAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:28e465d3-d73a-4bb3-bd60-c8c99c955ed6
Error Number:4060,State:1,Class:11
2018-08-26 10:17:05.346 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-26 10:17:05.362 -03:00 [DBG] Stopping token cleanup
2018-08-26 10:17:05.362 -03:00 [ERR] Unexpected exception in SocketConnection.StartAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
2018-08-26 10:17:05.362 -03:00 [ERR] Unexpected exception in SocketConnection.StartAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
2018-08-26 10:24:50.271 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 10:24:50.292 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 10:24:50.292 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 10:24:50.293 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 10:24:50.293 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 10:24:50.375 -03:00 [DBG] Starting token cleanup
2018-08-26 10:24:52.790 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 10:24:52.793 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 10:24:52.794 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 10:24:52.796 -03:00 [INF] Identity.Application was not authenticated. Failure message: No principal.
2018-08-26 10:24:52.809 -03:00 [INF] Identity.Application was not authenticated. Failure message: No principal.
2018-08-26 10:25:00.857 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 10:25:04.521 -03:00 [INF] AuthenticationScheme: Facebook was challenged.
2018-08-26 10:25:05.522 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 10:25:37.146 -03:00 [INF] User created a new account with password.
2018-08-26 10:25:42.081 -03:00 [INF] User created a new account with password.
2018-08-26 10:26:29.221 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Facebook",
  "ProviderUserId": "1832756710095231",
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGBAT6M9LTL:00000007",
  "TimeStamp": "2018-08-26T13:26:29Z",
  "ProcessId": 12080,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 10:26:29.240 -03:00 [DBG] Augmenting SignInContext
2018-08-26 10:26:29.241 -03:00 [DBG] Adding amr claim with value: external
2018-08-26 10:26:29.246 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 10:26:29.248 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 10:26:29.317 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 10:44:12.401 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 10:44:12.424 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 10:44:12.424 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 10:44:12.425 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 10:44:12.425 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 10:44:12.514 -03:00 [DBG] Starting token cleanup
2018-08-26 11:07:11.422 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 11:07:15.350 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 11:44:12.779 -03:00 [INF] Clearing 0 tokens
2018-08-26 11:58:23.595 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 11:58:23.619 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 11:58:23.620 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 11:58:23.620 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 11:58:23.621 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 11:58:23.729 -03:00 [DBG] Starting token cleanup
2018-08-26 12:00:36.224 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:05:02.347 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 12:05:02.372 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 12:05:02.372 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 12:05:02.372 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 12:05:02.373 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 12:05:02.466 -03:00 [DBG] Starting token cleanup
2018-08-26 12:09:19.255 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 12:09:19.277 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 12:09:19.277 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 12:09:19.277 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 12:09:19.278 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 12:09:19.365 -03:00 [DBG] Starting token cleanup
2018-08-26 12:38:23.199 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 12:38:23.221 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 12:38:23.222 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 12:38:23.222 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 12:38:23.222 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 12:38:23.314 -03:00 [DBG] Starting token cleanup
2018-08-26 12:39:18.035 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:39:57.414 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:40:03.282 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:45:13.799 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:45:51.028 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:46:10.637 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:48:50.231 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:55:00.788 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 12:55:00.811 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 12:55:00.811 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 12:55:00.812 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 12:55:00.812 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 12:55:00.884 -03:00 [DBG] Starting token cleanup
2018-08-26 12:55:03.988 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:57:02.414 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:57:34.764 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 12:57:44.984 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:50:03.391 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:52:37.819 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:53:15.258 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:53:40.701 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:55:00.914 -03:00 [INF] Clearing 0 tokens
2018-08-26 13:56:02.557 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:56:04.916 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 13:56:23.551 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:00:47.658 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:00:50.270 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:01:17.014 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:01:17.329 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper.Content(String contentPath)
   at AspNetCore.Views_Shared__Layout.<>c__DisplayClass9_0.<<ExecuteAsync>b__2>d.MoveNext() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Views\Shared\_Layout.cshtml:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Shared__Layout.ExecuteAsync() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Views\Shared\_Layout.cshtml:line 9
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:01:26.247 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:01:39.583 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:04:58.902 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:07:31.440 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:07:34.160 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:07:44.299 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:07:44.361 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 14:07:44.363 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:07:44.365 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 14:07:44.395 -03:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "ActivityId": "0HLGBDH3TLKGF:0000001A",
  "TimeStamp": "2018-08-26T17:07:44Z",
  "ProcessId": 27164,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:08:04.858 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:08:08.083 -03:00 [INF] AuthenticationScheme: Facebook was challenged.
2018-08-26 14:08:09.179 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:08:09.260 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Facebook",
  "ProviderUserId": "1832756710095231",
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGBDH3TLKGH:0000001C",
  "TimeStamp": "2018-08-26T17:08:09Z",
  "ProcessId": 27164,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:08:09.272 -03:00 [DBG] Augmenting SignInContext
2018-08-26 14:08:09.274 -03:00 [DBG] Adding amr claim with value: external
2018-08-26 14:08:09.279 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 14:08:09.280 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:08:09.314 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:09:00.048 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:09:55.693 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:10:01.947 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:10:05.105 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:11:31.052 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:11:43.948 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:12:32.623 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:14:46.192 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:14:46.202 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 14:14:46.203 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:14:46.207 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 14:14:46.209 -03:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "ActivityId": "0HLGBDH3TLKGH:0000003A",
  "TimeStamp": "2018-08-26T17:14:46Z",
  "ProcessId": 27164,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:15:14.770 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:15:24.270 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:16:10.104 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:16:10.137 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:16:10.137 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:16:10.138 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:16:10.138 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:16:10.235 -03:00 [DBG] Starting token cleanup
2018-08-26 14:17:12.908 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_LayoutExt.cshtml': 'breadcrumb'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:17:39.653 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_LayoutExt.cshtml': 'breadcrumb'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:20:17.582 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:20:23.379 -03:00 [INF] AuthenticationScheme: Facebook was challenged.
2018-08-26 14:20:24.502 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:20:24.777 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Facebook",
  "ProviderUserId": "1832756710095231",
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGBEUF3F4EN:00000010",
  "TimeStamp": "2018-08-26T17:20:24Z",
  "ProcessId": 23376,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:20:24.797 -03:00 [DBG] Augmenting SignInContext
2018-08-26 14:20:24.799 -03:00 [DBG] Adding amr claim with value: external
2018-08-26 14:20:24.804 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 14:20:24.809 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:20:24.867 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:22:21.235 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:22:54.703 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:22:58.455 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:23:19.024 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:24:34.569 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:25:13.648 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:25:13.688 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 14:25:13.690 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:25:13.691 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 14:25:13.697 -03:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "ActivityId": "0HLGBEUF3F4ET:0000001A",
  "TimeStamp": "2018-08-26T17:25:13Z",
  "ProcessId": 23376,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:25:26.984 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:25:28.899 -03:00 [INF] AuthenticationScheme: Facebook was challenged.
2018-08-26 14:25:29.763 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:25:29.785 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Facebook",
  "ProviderUserId": "1832756710095231",
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGBEUF3F4ET:00000022",
  "TimeStamp": "2018-08-26T17:25:29Z",
  "ProcessId": 23376,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:25:29.788 -03:00 [DBG] Augmenting SignInContext
2018-08-26 14:25:29.789 -03:00 [DBG] Adding amr claim with value: external
2018-08-26 14:25:29.790 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 14:25:29.793 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:25:29.802 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:27:31.659 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper.Content(String contentPath)
   at AspNetCore.Views_Home_Index.ExecuteAsync() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Views\Home\Index.cshtml:line 40
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:27:44.430 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:28:07.525 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:28:13.756 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:28:13.763 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 14:28:13.765 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:28:13.768 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 14:28:13.771 -03:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "ActivityId": "0HLGBEUF3F4ET:00000036",
  "TimeStamp": "2018-08-26T17:28:13Z",
  "ProcessId": 23376,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:28:20.254 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:29:28.298 -03:00 [DBG] CORS request made for path: /account/login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:29:50.961 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:30:45.156 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:30:51.262 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:31:32.916 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:31:32.946 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:31:32.946 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:31:32.947 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:31:32.947 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:31:33.039 -03:00 [DBG] Starting token cleanup
2018-08-26 14:31:37.170 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:31:38.246 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:31:42.412 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:31:50.500 -03:00 [WRN] User 82d5c53e-7e74-49d8-be65-116ebff07468 validation failed: DuplicateUserName.
2018-08-26 14:31:52.466 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at IdentityServer4.AspNetIdentity.UserClaimsFactory`1.CreateAsync(TUser user) in C:\local\identity\server4\AspNetIdentity\src\IdentityServer4.AspNetIdentity\UserClaimsFactory.cs:line 28
   at Microsoft.AspNetCore.Identity.SignInManager`1.CreateUserPrincipalAsync(TUser user)
   at Equinox.UI.SSO.Controllers.Account.AccountController.ExternalLoginCallback() in D:\workspace\JP.Project\src\Backend\Equinox.UI.SSO\Controllers\Account\AccountController.cs:line 213
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:32:08.505 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:32:39.157 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:33:10.829 -03:00 [WRN] User dd40c288-02fa-439e-85bf-b769b73c97b9 validation failed: DuplicateUserName.
2018-08-26 14:47:00.081 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:47:00.103 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:47:00.104 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:47:00.105 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:47:00.105 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:47:00.181 -03:00 [DBG] Starting token cleanup
2018-08-26 14:47:01.830 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:47:35.790 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:47:38.728 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:48:10.410 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:48:11.677 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:48:12.226 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:49:15.499 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:49:15.523 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:49:15.524 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:49:15.524 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:49:15.524 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:49:15.618 -03:00 [DBG] Starting token cleanup
2018-08-26 14:49:17.162 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'CanWriteCustomerData' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2018-08-26 14:51:29.097 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:51:29.122 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:51:29.123 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:51:29.123 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:51:29.123 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:51:29.208 -03:00 [DBG] Starting token cleanup
2018-08-26 14:51:33.847 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:51:38.516 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:51:55.010 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:52:04.865 -03:00 [WRN] User 37d96e4c-68ab-431c-a8c5-ce12ceebe00e validation failed: DuplicateUserName.
2018-08-26 14:52:28.597 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:52:29.585 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:52:33.646 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:52:41.381 -03:00 [WRN] User 2a5dd590-4799-44b6-827c-3b5f31de946d validation failed: DuplicateUserName.
2018-08-26 14:55:19.564 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:55:19.588 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:55:19.589 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:55:19.589 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:55:19.589 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:55:19.687 -03:00 [DBG] Starting token cleanup
2018-08-26 14:55:24.508 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:55:26.380 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:55:32.019 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:55:32.201 -03:00 [WRN] User 2e4d13a1-a9e1-4325-88b8-5d64753ef5d0 validation failed: DuplicateUserName.
2018-08-26 14:56:45.334 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:56:45.360 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:56:45.360 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:56:45.361 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:56:45.361 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:56:45.455 -03:00 [DBG] Starting token cleanup
2018-08-26 14:56:49.484 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:56:50.803 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:56:55.512 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:56:55.684 -03:00 [WRN] User 968650d3-f632-4b0b-8fcc-903474ef27e9 validation failed: DuplicateUserName.
2018-08-26 14:57:49.282 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 14:57:49.306 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 14:57:49.306 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 14:57:49.307 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 14:57:49.307 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 14:57:49.397 -03:00 [DBG] Starting token cleanup
2018-08-26 14:57:53.850 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 14:57:55.679 -03:00 [INF] AuthenticationScheme: Facebook was challenged.
2018-08-26 14:57:56.592 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:57:56.860 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Provider": "Facebook",
  "ProviderUserId": "1832756710095231",
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "Endpoint": "UI",
  "ActivityId": "0HLGBFLNT0BL7:00000006",
  "TimeStamp": "2018-08-26T17:57:56Z",
  "ProcessId": 10476,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:57:56.878 -03:00 [DBG] Augmenting SignInContext
2018-08-26 14:57:56.880 -03:00 [DBG] Adding amr claim with value: external
2018-08-26 14:57:56.885 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 14:57:56.890 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:57:56.946 -03:00 [DBG] 0 persisted grants found for 86cab393-f5a8-46f9-9abc-1f7be2b2e5e2
2018-08-26 14:58:01.720 -03:00 [DBG] CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 14:58:01.756 -03:00 [INF] AuthenticationScheme: Identity.Application signed out.
2018-08-26 14:58:01.758 -03:00 [INF] AuthenticationScheme: Identity.External signed out.
2018-08-26 14:58:01.759 -03:00 [INF] AuthenticationScheme: Identity.TwoFactorUserId signed out.
2018-08-26 14:58:01.766 -03:00 [INF] {
  "Name": "User Logout Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1002,
  "SubjectId": "86cab393-f5a8-46f9-9abc-1f7be2b2e5e2",
  "DisplayName": "Bruno Brito",
  "ActivityId": "0HLGBFLNT0BL7:0000000A",
  "TimeStamp": "2018-08-26T17:58:01Z",
  "ProcessId": 10476,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 14:59:24.843 -03:00 [INF] AuthenticationScheme: Google was challenged.
2018-08-26 14:59:28.997 -03:00 [INF] AuthenticationScheme: idsrv.external signed in.
2018-08-26 14:59:29.156 -03:00 [WRN] User 619f1fdb-0dd2-413c-ae63-b59f973a1207 validation failed: DuplicateUserName.
2018-08-26 14:59:38.454 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 15:00:30.138 -03:00 [DBG] CORS request made for path: /account/login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 15:03:03.922 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 15:03:03.957 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 15:03:03.957 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 15:03:03.958 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 15:03:03.958 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 15:03:04.138 -03:00 [DBG] Starting token cleanup
2018-08-26 15:03:27.898 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 15:03:39.727 -03:00 [DBG] CORS request made for path: /account/login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 15:03:55.086 -03:00 [DBG] Augmenting SignInContext
2018-08-26 15:03:55.096 -03:00 [DBG] Adding idp claim with value: local
2018-08-26 15:03:55.096 -03:00 [DBG] Adding amr claim with value: pwd
2018-08-26 15:03:55.098 -03:00 [DBG] Adding auth_time claim with value: 1535306635
2018-08-26 15:03:55.111 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 15:04:04.626 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "bruno",
  "SubjectId": "c4b6b328-21ca-4438-022d-08d60b6c46e1",
  "DisplayName": "bruno",
  "Endpoint": "UI",
  "ActivityId": "0HLGBFOLMFRPC:00000005",
  "TimeStamp": "2018-08-26T18:04:04Z",
  "ProcessId": 31448,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 15:04:50.862 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 15:04:50.890 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 15:04:50.890 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 15:04:50.890 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 15:04:50.890 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 15:04:50.987 -03:00 [DBG] Starting token cleanup
2018-08-26 15:04:56.045 -03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2018-08-26 15:05:00.490 -03:00 [DBG] CORS request made for path: /account/login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2018-08-26 15:05:08.438 -03:00 [DBG] Augmenting SignInContext
2018-08-26 15:05:08.447 -03:00 [DBG] Adding idp claim with value: local
2018-08-26 15:05:08.448 -03:00 [DBG] Adding amr claim with value: pwd
2018-08-26 15:05:08.450 -03:00 [DBG] Adding auth_time claim with value: 1535306708
2018-08-26 15:05:08.460 -03:00 [INF] AuthenticationScheme: Identity.Application signed in.
2018-08-26 15:05:12.090 -03:00 [INF] {
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "bruno",
  "SubjectId": "c4b6b328-21ca-4438-022d-08d60b6c46e1",
  "DisplayName": "bruno",
  "Endpoint": "UI",
  "ActivityId": "0HLGBFPLJ5MRJ:00000004",
  "TimeStamp": "2018-08-26T18:05:12Z",
  "ProcessId": 2604,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}
2018-08-26 15:05:17.987 -03:00 [DBG] 0 persisted grants found for c4b6b328-21ca-4438-022d-08d60b6c46e1
2018-08-26 15:05:29.542 -03:00 [DBG] 0 persisted grants found for c4b6b328-21ca-4438-022d-08d60b6c46e1
2018-08-26 15:05:39.454 -03:00 [DBG] 0 persisted grants found for c4b6b328-21ca-4438-022d-08d60b6c46e1
2018-08-26 15:07:31.243 -03:00 [DBG] Using Identity.Application as default scheme for authentication
2018-08-26 15:07:31.274 -03:00 [DBG] Using Identity.External as default scheme for sign-in
2018-08-26 15:07:31.275 -03:00 [DBG] Using Identity.External as default scheme for sign-out
2018-08-26 15:07:31.276 -03:00 [DBG] Using Identity.Application as default scheme for challenge
2018-08-26 15:07:31.276 -03:00 [DBG] Using Identity.Application as default scheme for forbid
2018-08-26 15:07:31.399 -03:00 [DBG] Starting token cleanup
2018-08-26 15:07:43.601 -03:00 [DBG] TaskCanceledException. Exiting.
2018-08-26 15:07:43.620 -03:00 [DBG] Stopping token cleanup
